[package]
name = "rs_table_renderer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
magnus = "0.3"
chrono = "0.4.23"
html-escape = "0.2.13"
