# frozen_string_literal: true

require "bundler/gem_tasks"
task default: %i[]

require "rake/extensiontask"
Rake::ExtensionTask.new("rs_table_renderer") do |ext|
  ext.lib_dir = "lib/rs_table_renderer"
  ext.source_pattern = "*.{rs,toml}"
end
